config/routes.rb
Gmaps::Application.routes.draw do
  get 'investigators/index'

  resources :cars

  root 'cars#index'
  get  'nonauth'    => 'cars#nonauthorised'
  get  'update_map' => 'cars#update_map'
end

app/models/car.rb
class Car < ActiveRecord::Base
  VALID_CARS_NUMBER = /[A-Z]{2}[\d]{4}[A-Z]{2}/
  VALID_VIM_NUM_REGEX = /\w{15,20}/
  VALID_CARS_NAME = /[0-9]{4}/

  validates :car_number,
          presence: { message: " не може бути порожньою" } ,
          uniqueness:  {case_sensitive: false, message: " вже зареєстровано"},
          format: { with: VALID_CARS_NUMBER, message: "має неправильний формат" }

  validates :vin_number,
          presence: { message: " не може бути порожнім" },
          uniqueness:  {case_sensitive: false, message: " вже зареєстровано"},
          format: { with: VALID_VIM_NUM_REGEX, message: "має неправильний формат" }

  validates :car_name,
          presence: { message: " не може бути порожнім" },
          uniqueness:  {case_sensitive: false, message: " вже зареєстровано"},
          format: { with: VALID_CARS_NAME, message: "має неправильний формат" }

  def self.extract_car name, vin, number
    find_by("car_number = ? AND vin_number = ? AND car_name = ?", number, vin, name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  #before_action :check_api_key, only: [:index, :update_map, :new, :edit, :create, :update, :destroy]
  before_action :get_markers, only: [:index, :update_map]
  def index
  end

  def update_map
    respond_to do |format|
      format.js {}
      format.json { render json: @hash }
    end
  end

  def get_markers
    @cars = Car.where(deleted: false)
    @hash = Gmaps4rails.build_markers(@cars) do |car, marker|
      marker.lat car.latitude
      marker.lng car.longitude
      marker.title "Екіпаж: #{car.car_name}"
      marker.infowindow "Екіпаж #{car.car_name}, держ. знак #{car.car_number}"
    end
  end

  def show
    @car = Car.find(params[:id])
  end

  def new
    @car = Car.new
  end

  def edit
    @car = Car.find(params[:id])
  end

  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was created successfully.' }
        format.json { render action: 'show', status: :created, location: @car }
      else
        format.html { render action: 'new' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update(car_update_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.'}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      if Car.find(params[:id]).update_attribute(:deleted, true)
        format.html { redirect_to @car, notice: 'Car was successfully deleted.'}
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def check_api_key
      if (!params[:key].eql? APP_CONFIG['key']) || params[:key].nil?
        puts "======================== WRONG API KEY! ========================="
        respond_to do |format|
          format.html { redirect_to nonauth_path }
          format.json { render nothing: true, status: :unauthorized }
        end
      end
    end

    def car_params
      params.require(:car).permit(:car_number, :vin_number, :car_name)
    end

    def car_update_params
      params.require(:car).permit(:car_number,
                                  :vin_number, :car_name,
                                  :longitude, :latitude,
                                  :on_duty, :on_a_mission)
    end
end

app/controllers/investigators_controller.rb
class InvestigatorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/investigators_helper.rb
module InvestigatorsHelper
end

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :car_number %><br>
    <%= f.text_field :car_number %>
  </div>
  <div class="field">
    <%= f.label :vin_number %><br>
    <%= f.text_field :vin_number %>
  </div>
  <div class="field">
    <%= f.label :car_name %><br>
    <%= f.text_field :car_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<div class="form_list">
  <h1>Editing Car</h1>

  <%= form_for(@car) do |f| %>
    <% if @car.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

        <ul>
        <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :car_number %><br>
      <%= f.text_field :car_number %>
    </div>
    <div class="field">
      <%= f.label :vin_number %><br>
      <%= f.text_field :vin_number %>
    </div>
    <div class="field">
      <%= f.label :car_name %><br>
      <%= f.text_field :car_name %>
    </div>
    <div class="field">
      <%= f.label :latitude %><br>
      <%= f.text_field :latitude %>
    </div>
    <div class="field">
      <%= f.label :longitude %><br>
      <%= f.text_field :longitude %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <%= link_to 'Show', @car %> |
  <%= link_to 'Back', cars_path %>
</div>

app/views/cars/index.html.erb
<%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=geometry&key=#{APP_CONFIG['google-map-key']}" %>

<div class="container-fluid">
  <div class="row spacing-fix" >
    <div class="col-md-3 spacing-fix list-over-map">
      <%= render "shared/header" %>
      <div class="card-row">
      <h3 id="list-header">Список екіпажів</h3>
        <div class="panel-group">
          <%= render partial: "partials/car", collection: @cars  %>
        </div>
      </div>
    </div>
    <div class="col-md-9 spacing-fix list-over-map">
      <%= render "partials/search" %>
    </div>
    <%= render "shared/map" %>
  </div>
</div>

app/views/cars/new.html.erb
<div class="form_list">
  <h1>New Car</h1>
  <%= render 'form' %>
  <%= link_to 'Back', cars_path %>
</div>

app/views/cars/nonauthorised.html.erb
<h2>You don't have permition to access this information</h2>

app/views/cars/show.html.erb
<div class="form_list">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Number:</strong>
    <%= @car.car_number %>
  </p>

  <p>
    <strong>VIN:</strong>
    <%= @car.vin_number %>
  </p>

  <p>
    <strong>Crew name:</strong>
    <%= @car.car_name %>
  </p>

  <%= @car.deleted ? "Видалено" : "Не видалено" %>

  <%= link_to 'Edit', edit_car_path(@car) %> |
  <%= link_to 'Back', cars_path %>
</div>

app/views/investigators/index.html.erb
<h1>Investigators#index</h1>
<p>Find me in app/views/investigators/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Моніторінг екіпажів</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_car.html.erb
<div class="panel">
  <div class="panel-heading">
    <h4 class="panel-title">
      <%= link_to "Екіпаж: " + car.car_name, "#" + car.car_name, data: { toggle: "collapse" } %>
      <div class="pull-right">
        <% if !car.on_duty?%>
          <span class="glyphicon glyphicon-ban-circle broken-car"
                aria-hidden="true" data-container="body"
                data-toggle="popover" data-placement="right"
                data-content="На ремонті" ></span>
        <% end %>
      </div>
    </h4>
  </div>
  <div id="<%= car.car_name %>" class="panel-collapse collapse">
    <div class="panel-body">
      <ul class="properties-list">
        <li>Оновлено: <%= car.updated_at.strftime("%H:%m %B, %d") %></li>
        <li>Номер: <%= car.car_number %>, <%= link_to "налаштування", edit_car_path(car) %></li>
        <li>
          Статус: <%= car.on_a_mission? ? "на виїзді" : "вільний" %><%= sanitize(", <b>у ремонті</b>") if !car.on_duty? %>
        </li>
      <ul>
    </div>
  </div>
</div>

app/views/partials/_search.html.erb
<div class="search-panel">
  <input type="text" class="search-form" id="search_query" placeholder="Пошук екіпажів на мапі" name="search">
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default topnav" id="card-header" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header hiden-xs">
      <%= link_to root_path, class: "navbar-brand" do  %>
        <%= image_tag "system/gerald.gif", class: "gerald", alt: "Сервер екіпажів"%>
      <% end %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Сервер екіпажів", root_path, class: "brand-name", data: { "no-turbolink": true }  %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right hidden-xs">
      <li class="pull-right">
        <%= link_to "#", class: "navbar-link", id: "search-icon" do %>
          <span class="glyphicon glyphicon-search" ></span>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_map.html.erb
<div id="map-container">
  <div id="map-canvas"></div>
</div>
<script>

/**
**            Map initializing
**/

  var map = new GMaps({
    el: '#map-canvas',
    lat: 50.27,
    lng: 30.3125,
    zoom: 10,
    disableDefaultUI: true
  });

/**
 *            Live map update with AJAX queries
 **/

var delay = 5000,                                                               // Delay in microseconds to update markers on map

callout = function () {
  $.ajax({
    type: 'GET',
    url: '/update_map',
    async: true,
    beforeSend: function (xhr) {
      if (xhr && xhr.overrideMimeType) {
        xhr.overrideMimeType('application/json;charset=utf-8');
      }
    },
    dataType: 'json',
    success: function (data) {
      map.removeMarkers();
      map.addMarkers(data);
    }
  }).always(function () {
      setTimeout(callout, delay);
  });
};
callout();

function move_map_to (latitude, longitude) {                                    // Interface to move center of map to the specific place
  map.map.panTo({lat: latitude, lng: longitude});
}


/**
**              Autocomplete function for live search
**/

  $("#search_query").autocomplete({
    source: function (request, response) {
       var matcher = new RegExp($.ui.autocomplete.escapeRegex(request.term), "i");
       var array = $.grep(<%= raw @cars.to_json %>, function (value) {          // Get all crew from list, that already listed in the first request
           return matcher.test(value.car_name) || matcher.test(value.car_number);
       });
       response(array);
    },
    select: function (event, ui) {
      $.ajax({                                                                  // Get fresh information about crew's position
        type: 'GET',
        url: '/cars/' + ui.item.id,
        async: true,
        beforeSend: function (xhr) {
          if (xhr && xhr.overrideMimeType) {
            xhr.overrideMimeType('application/json;charset=utf-8');
          }
        },
        dataType: 'json',
        success: function (data) {
          $("#search_query").val("Екіпаж " + ui.item.car_name + ", держ. знак " + ui.item.car_number);
          move_map_to(data.latitude, data.longitude);
        }
      });
    }
  }).data("uiAutocomplete")._renderItem = function(ul, item) {
      return $("<li></li>").data("item.autocomplete", item).append("<a>Екіпаж " + item.car_name +  ", держ. знак " + item.car_number + "</a>").appendTo(ul);
  };
</script>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>

<div>
  <div id="list">
    <h1>List of Cars</h1>
    <h6><%= link_to "New Car", new_user_path %></h6>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Latitude</th>
          <th>Longitude</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.title %></td>
            <td><%= user.latitude %></td>
            <td><%= user.longitude %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div id="map-container">
    <div id="map-canvas"></div>
  </div>
</div>

<script type="text/javascript">
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map-canvas'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>